name: Dr Header Release Task

on: 
  push:
    branches: [ test-bumpversion ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
        matrix:
          python-version: [3.7]
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements_dev.txt
            
      - name: BumpVersion
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          bumpversion minor
      
      - name: Test with Nosetests
        run: python -m nose --with-xunit --xunit-file=${{ matrix.python-version }}.results.xml

      - name: Flake8 styles
        run: python -m flake8 drheader

      - name: Bandit security scan
        run: python -m bandit -r ./drheader

      - name: Safety dependency scan
        run: python -m safety check

      - name: Get bumpversion
        run: echo ::set-env name=VERSION::$(grep -i 'current_version = ' setup.cfg |  tr -d 'current_version = ')  
